contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #tva channel"
    url: https://nfcore.slack.com/channels/tva
    about: Discussion about the nf-core/tva pipeline
